### ISSUE TITLE
Ghosting in 3D rendering

### ISSUE THREAD

**Issue by 934556826** [Kitware/glance#473]
![image](https://github.com/Kitware/glance/assets/55786312/a5949a9b-5600-43c1-9976-08898c77328d)
open in Microsoft Edge/113.0.1774.42

**Comment by aylward** [comment]
@934556826 - did you try other browsers?   

Thanks for providing info on the browser you are using.   I can confirm that this happens in that version of Microsoft Edge.    Additionally, this is now also happening in my version of Chrome: 

This issue is the same as this previous report that was closed:
https://github.com/Kitware/glance/issues/472
